network:
  version: 2
  ethernets:
    ens3:
      dhcp4: true
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
          - 1.1.1.1
    ens4:
      dhcp4: false
      addresses:
        - 192.168.100.51/24
