---
# Версии компонентов
kube_version: "1.33.1"
kube_version_major: "1.33"
calico_version: "v3.30.0"
containerd_version: "2.1.0"
runc_version: "v1.3.0"
cni_plugins_version: "1.7.1"
ingress_nginx_version: "4.12.2"
ingress_nginx_namespace: "ingress-nginx"

containerd_url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
containerd_url_checksum: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz.sha256sum"
runc_url: "https://github.com/opencontainers/runc/releases/download/{{ runc_version }}/runc.amd64"
runc_asc: "https://github.com/opencontainers/runc/releases/download/{{ runc_version }}/runc.amd64.asc"
cni_plugins_url: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-linux-amd64-v1.7.1.tgz"
cni_url_checksum: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-linux-amd64-v1.7.1.tgz.sha256"

runc:
  pgp:
    expected_fingerprint: "5F36 C6C6 1B54 6012 4A75  F5A6 9E18 AA26 7DDB 8DB4"  # Пример для runc 1.3.0
    # короткий айди через curl -sSL https://github.com/opencontainers/runc/releases/download/v1.3.0/runc.amd64.asc | gpg --list-packets
    key_id: "9E18AA267DDB8DB4"

manifests_dir: "/opt/k8s/manifests"
# Настройки сети
calico_pod_cidr: "10.244.0.0/16"
calico_block_size: 26
calico_encapsulation: "VXLANCrossSubnet"
calico_nat_outgoing: "Enabled"

# Ресурсы
calico_control_plane_replicas: 2

# Настройки kubeadm
kubeadm_init_command: |
  kubeadm init \
  --pod-network-cidr {{ pod_network_cidr }} \
  --kubernetes-version {{ kube_version }} \
  --node-name {{ inventory_hostname }}

# URLs
calico_operator_url: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/tigera-operator.yaml"
calico_custom_resources_url: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/custom-resources.yaml"

# Настройки для всех узлов

common_system_packages:
  - apt-transport-https
  - curl
  - ca-certificates
  - gpg
  - software-properties-common

#grafana
grafana_admin_password: "z123456789z"
prometheus_namespace: "monitoring"