---
# Component versions
kube_version: "1.33.1"                     # Kubernetes version (full)
kube_version_major: "1.33"                  # Kubernetes major version for repo
calico_version: "v3.30.0"                   # Calico CNI version
containerd_version: "2.1.0"                 # Containerd runtime version
runc_version: "v1.3.0"                      # Runc container runtime version
cni_plugins_version: "1.7.1"                # CNI plugins version
ingress_nginx_version: "4.12.2"             # Ingress NGINX controller version
ingress_nginx_namespace: "ingress-nginx"    # Namespace for ingress controller

# Download URLs for components
containerd_url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
containerd_url_checksum: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz.sha256sum"
runc_url: "https://github.com/opencontainers/runc/releases/download/{{ runc_version }}/runc.amd64"
runc_asc: "https://github.com/opencontainers/runc/releases/download/{{ runc_version }}/runc.amd64.asc"
cni_plugins_url: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-linux-amd64-v1.7.1.tgz"
cni_url_checksum: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-linux-amd64-v1.7.1.tgz.sha256"

# PGP verification settings for runc
runc:
  pgp:
    expected_fingerprint: "5F36 C6C6 1B54 6012 4A75  F5A6 9E18 AA26 7DDB 8DB4"  # runc 1.3.0 fingerprint
    key_id: "9E18AA267DDB8DB4"                # PGP key ID for verification

# Kubernetes manifests directory
manifests_dir: "/opt/k8s/manifests"

# Network configuration
calico_pod_cidr: "10.244.0.0/16"            # Pod network CIDR
calico_block_size: 26                        # IP block size for Calico IPAM
calico_encapsulation: "VXLANCrossSubnet"     # Networking encapsulation method
calico_nat_outgoing: "Enabled"               # Enable NAT for outgoing traffic

# Cluster resources
calico_control_plane_replicas: 2            # Number of control plane replicas

# kubeadm initialization command template
kubeadm_init_command: |
  kubeadm init \
  --pod-network-cidr {{ pod_network_cidr }} \
  --kubernetes-version {{ kube_version }} \
  --node-name {{ inventory_hostname }}

# Calico deployment URLs
calico_operator_url: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/tigera-operator.yaml"
calico_custom_resources_url: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/custom-resources.yaml"

# Common system packages for all nodes
common_system_packages:
  - apt-transport-https       # HTTPS support for apt
  - curl                      # HTTP client
  - ca-certificates           # SSL certificates
  - gpg                       # GPG encryption
  - software-properties-common # Managing software repositories

# Monitoring credentials
grafana_admin_password: "z123456789z"       # Grafana admin password
prometheus_namespace: "monitoring"          # Namespace for monitoring stack