---
- name: Configure containerd runtime
  hosts: all
  become: yes
  vars_files:
    - vars.yml

  tasks:
    # 1.  Setup containerd modules
    - name: Ensure containerd.conf file exists
      ansible.builtin.file:
        path: /etc/modules-load.d/containerd.conf
        state: touch
        mode: '0644'

    - name: Add modules to containerd.conf
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/containerd.conf
        line: "{{ item }}"
        state: present
      loop:
        - "overlay"
        - "br_netfilter"
    # 5. Setup sysctl for Kubernetes
    - name: Ensure 99-kubernetes-cri.conf file exists
      ansible.builtin.file:
        path: /etc/sysctl.d/99-kubernetes-cri.conf
        state: touch
        mode: '0644'

    - name: Add sysctl settings for Kubernetes
      ansible.builtin.lineinfile:
        path: /etc/sysctl.d/99-kubernetes-cri.conf
        line: "{{ item }}"
        state: present
      loop:
        - "net.bridge.bridge-nf-call-iptables = 1"
        - "net.ipv4.ip_forward = 1"
        - "net.bridge.bridge-nf-call-ip6tables = 1"

    - name: Apply sysctl settings
      ansible.builtin.shell: sysctl --system
    # 6. Install Containerd
    
    - name: Download Containerd archive
      ansible.builtin.get_url:
        url: "{{ containerd_url }}"
        dest: "/tmp/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
        mode: '0644'

    - name: Extract Containerd archive
      ansible.builtin.unarchive:
        src: "/tmp/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
        dest: "/tmp/"
        remote_src: yes
    - name: Extract Containerd archive to /usr/local
      ansible.builtin.command:
        cmd: tar Cxzvf /usr/local /tmp/containerd-{{ containerd_version }}-linux-amd64.tar.gz
      become: yes
    - name: Get Containerd version
      ansible.builtin.command:
        cmd: containerd --version
      register: containerd_version_output


    - name: Print Containerd version
      debug:
        msg: "Containerd installed: {{ containerd_version_output.stdout }}"
    # 7. Install containerd.service
    - name: Download containerd systemd service file
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
        dest: /etc/systemd/system/containerd.service
        mode: '0644'

    - name: Reload systemd manager configuration
      ansible.builtin.shell: systemctl daemon-reload

    - name: Enable and start containerd service
      ansible.builtin.systemd:
        name: containerd
        enabled: true
        state: started